### ISSUE TITLE
add quarto jupyterlab extension

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/corn#21]
Would be great to add the Quarto extension for JupyterLab to corn: 

https://quarto.org/docs/tools/jupyter-lab-extension.html

> "The Quarto JuptyerLab extension enables JupyterLab Notebooks which use Quarto markdown to properly display the contents of the markdown cells. For example, when the Quarto JupyterLab extension is installed, your Notebook will show rendered previews of elements like Callouts, Divs, Mermaid charts, as well as other Quarto elements (including the document front matter as a title block)."

**Comment by ateucher** [comment]
This was done by @betolink here: https://github.com/NASA-Openscapes/corn/commit/af5b3dcac43e83a233f916a23bac15bb43e4969c#diff-08c8eb6bba623bea3fc66e52cd0b332b610f35d41b6a1bbb0fea9d204a97ba97R2
